### ISSUE TITLE
dir_all should recusively ignore sub-folders

### ISSUE THREAD

**Issue by rlorenzo** [njgibbon/fend#5]
In my .fend.yaml file I have this defined:

```
skip:
  dir_all:
    - wp-content/uploads/
```

However, when I run fend locally I still get errors about files that are in sub-folders in that directory.

Like wp-content/uploads/wpallimport/uploads/61363ae769ee1cf0dd96683fe1ad5dcf/index.php

I would expect dir_all to exclude that directory and all following directories

**Comment by njgibbon** [comment]
Hey @rlorenzo,  

`skip.dir_all` is meant to skip all instances of a folder. So for instance, if you define `temp` then scanning would skip every `temp` directory (and sub-directory) across the entire repository. So e.g `temp`, `a/b/temp`, `c/d/temp` would all be skipped. It's only expected to work with single folder strings because the other type of skip is meant for skipping paths.

`skip.dir` is meant to skip a specific folder and all sub-directories and so this is what you should use for this case.

So, right now the following skip config would do what you expect.

```
skip:
  dir:
    - wp-content/uploads
```

**Comment by rlorenzo** [comment]
@njgibbon Sorry about that. I changed my file to just dir and it works as expected.
